"""Compatibility imports for the canonical shared turn-dynamics model."""

from .turn_dynamics import (
    EARTH_RADIUS_M,
    GRAVITY_MPS2,
    MAX_PROJECTION_S,
    TurnPerformance,
    TurnPrediction,
    advance_roll_toward_target,
    bank_angle_for_turn_radius_deg,
    bank_angle_for_turn_rate_deg,
    coordinated_turn_rate_nav_dps,
    estimate_angular_rate_dps,
    estimate_linear_rate,
    fuse_turn_rate_nav_dps,
    normalize_attitude,
    predict_turn_motion,
    project_attitude_motion,
    shortest_heading_error_deg,
    turn_radius_from_bank_m,
    turn_radius_from_rate_m,
    turn_rate_for_radius_nav_dps,
    turn_rate_for_radius_rad_s,
)

__all__ = [
    "EARTH_RADIUS_M",
    "GRAVITY_MPS2",
    "MAX_PROJECTION_S",
    "TurnPerformance",
    "TurnPrediction",
    "advance_roll_toward_target",
    "bank_angle_for_turn_radius_deg",
    "bank_angle_for_turn_rate_deg",
    "coordinated_turn_rate_nav_dps",
    "estimate_angular_rate_dps",
    "estimate_linear_rate",
    "fuse_turn_rate_nav_dps",
    "normalize_attitude",
    "predict_turn_motion",
    "project_attitude_motion",
    "shortest_heading_error_deg",
    "turn_radius_from_bank_m",
    "turn_radius_from_rate_m",
    "turn_rate_for_radius_nav_dps",
    "turn_rate_for_radius_rad_s",
]
