# -*- coding: utf-8 -*-
import json
from pathlib import Path

path = Path(r"modules/monitoring_ver2/logic/replan_actual_logic.py")
text = path.read_text(encoding="utf-8")
old = "    if msg_id == \"0802\":\n        mandatory_desc = {\n            1: \"媛뺤젣?湲곕줈 ?명븳 ?ш퀎??,\n            2: \"媛뺤젣洹?섏쑝濡??명븳 ?ш퀎??,\n            3: \"媛뺤젣?꾨Т蹂듦?濡??명븳 ?ш퀎??,\n        }.get(_extract_mandatory_type(detail))\n        return mandatory_desc or \"媛뺤젣紐낅졊?쇰줈 ?명븳 ?ш퀎??\n\n    return _serialize_reason(replan_info)\n"
new = "    if msg_id == \"0802\":\n        mandatory_desc = {\n            1: \"강제대기로 인한 재계획\",\n            2: \"강제귀환으로 인한 재계획\",\n            3: \"강제임무복귀로 인한 재계획\",\n        }.get(_extract_mandatory_type(detail))\n        return mandatory_desc or \"강제명령으로 인한 재계획\"\n\n    if msg_id == \"0402\":\n        detail_obj = None\n        if isinstance(detail, str):\n            try:\n                detail_obj = json.loads(detail)\n            except Exception:\n                detail_obj = None\n        elif isinstance(detail, dict):\n            detail_obj = detail\n        targets = []\n        if isinstance(detail_obj, dict):\n            maybe_targets = detail_obj.get(\"targets\")\n            if isinstance(maybe_targets, list):\n                targets = maybe_targets\n        elif isinstance(detail, list):\n            targets = detail\n\n        summary_parts = []\n        for target in targets:\n            if not isinstance(target, dict):\n                continue\n            watcher_raw = target.get(\"watcherID\")\n            target_raw = target.get(\"targetID\")\n            type_raw = target.get(\"targetType\")\n            try:\n                watcher_id = int(watcher_raw) if watcher_raw is not None else None\n            except (TypeError, ValueError):\n                watcher_id = None\n            try:\n                target_id = int(target_raw) if target_raw is not None else None\n            except (TypeError, ValueError):\n                target_id = None\n            try:\n                type_id = int(type_raw) if type_raw is not None else None\n            except (TypeError, ValueError):\n                type_id = None\n\n            watcher_label = f"{watcher_id}번 무인기" if watcher_id is not None else "무인기"
            target_label = f"target ID {target_id}번" if target_id is not None else f"target ID {target_raw}"
            type_name = TARGET_TYPE_LABELS.get(type_id, "알 수 없음")\n            summary_parts.append(f"{watcher_label}의 {target_label}({type_name}) 최초 발견")\n\n        if summary_parts:\n            return "0402 신규 표적 감지: " + "; ".join(summary_parts)\n        return "0402 신규 표적 감지"\n\n    return _serialize_reason(replan_info)\n"
if old not in text:
    raise SystemExit("pattern not found")
text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
