# receive/__init__.py

from dll_files.nFusionImports import FusionNodeIoc

# ① 각 리시버 모듈 import
from .message0000_receiver   import ResponseReceiver_0000
from .message0101_receiver   import SystemOperationModeReceiver_0101
from .message0201_receiver   import InputMissionPlanReceiver_0201
from .message0202_receiver   import PriorMissionInfoReceiver_0202
from .message0203_receiver   import FlightReferenceInfoReceiver_0203
from .message0301_receiver   import MissionPlanReceiver_0301
from .message0302_receiver   import IndividualMissionPlanReceiver_0302
from .message0303_receiver   import UAVFlightPlanReceiver_0303
from .message0304_receiver   import LAHFlightPlanReceiver_0304
from .message0401_receiver   import LAHStatusReceiver_0401
from .message0402_receiver   import SituationAwarenessInfoReceiver_0402
from .message0501_receiver   import MissionStateInfoReceiver_0501
from .message0701_receiver   import MissionPlanOptionReceiver_0701
from .message0702_receiver   import MissionProgressReceiver_0702
from .message0801_receiver   import ReplanCommandReceiver_0801
from .message0802_receiver   import MandatoryCommandReceiver_0802
from .message0803_receiver   import StartNextMissionCommandReceiver_0803
# from .message0804_receiver   import MissionRestartCommandReceiver_0804
from .message0805_receiver   import EndMissionCommandReceiver_0805
from .message0806_receiver   import EndSWCommandReceiver_0806
from .message0901_receiver   import RequestOptionInfoReceiver_0901
from .message0902_receiver   import ReplanRequestReceiver_0902
from .message0903_receiver   import RequestRenewMissionReceiver_0903

FusionNodeIoc.AddConsumerFromAssemblyContainsType(ResponseReceiver_0000)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(SystemOperationModeReceiver_0101)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(InputMissionPlanReceiver_0201)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(PriorMissionInfoReceiver_0202)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(FlightReferenceInfoReceiver_0203)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MissionPlanReceiver_0301)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(IndividualMissionPlanReceiver_0302)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(UAVFlightPlanReceiver_0303)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(LAHFlightPlanReceiver_0304)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(LAHStatusReceiver_0401)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(SituationAwarenessInfoReceiver_0402)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MissionStateInfoReceiver_0501)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MissionPlanOptionInfoReceiver_0701)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MissionProgressReceiver_0702)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(ReplanCommandReceiver_0801)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MandatoryCommandReceiver_0802)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(StartNextMissionCommandReceiver_0803)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(MissionRestartCommandReceiver_0804)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(EndMissionCommandReceiver_0805)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(EndSWCommandReceiver_0806)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(RequestOptionInfoReceiver_0901)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(ReplanRequestReceiver_0902)
# FusionNodeIoc.AddConsumerFromAssemblyContainsType(RequestRenewMissionReceiver_0903)
